### ISSUE TITLE
Emerald-derived backgrounds for Debian Edu

### ISSUE THREAD

**Issue by sunweaver** [julietteTaka/Emerald#4]
Dear Juliette,

for past Debian Edu blend of Debian, we used to ship background images that had been derived from the default Debian desktop themes of the corresponding Debian release.

Debian Edu is a Debian blend / customization targetting usage of Debian in schools. [0]

For Debian Edu squeeze (long ago) we had a brilliant redesign [1] of Debian's original spacefun theme [2].

For later Debian Edu releases, the Edu theme was not as playful and individual as the Debian Edu squeeze theme. See here: [3], [4], [5]. The Debian Edu developer who created those latter artworks has left the project recently and we are currently re-thinking Debian Edu artwork maintenance.

I probably could work on a minimal derivation of the original Emerald background images myself, but maybe you could come up with something more creative? (I definitely assume that!!!) Some background artwork that resembles Emerald theming but also let's people think of Education, young people, etc.

@highvoltage mentioned on IRC a while back that it could be an option to ask you about this directly. So here comes the official question if you can imagine working on some Debian Edu 12 artwork. Thanks in advance for any feedback given. We'd be honoured to have some official Edu Emerald theming created by you, definitely.

light+love
Mike (aka sunweaver at debian.org)

[0] https://blends.debian.org/edu/
[1] https://salsa.debian.org/debian-edu/debian-edu-artwork-legacy/-/blob/master/art-spacefun/desktop-base/1920x1080.svg
[2] https://wiki.debian.org/DebianArt/Themes/SpaceFun
[3] https://salsa.debian.org/debian-edu/debian-edu-artwork/-/blob/master/art-buster/desktop-base/1920x1080.svg
[4] https://salsa.debian.org/debian-edu/debian-edu-artwork/-/blob/master/art-softwaves/desktop-base/1920x1080.svg
[5] https://salsa.debian.org/debian-edu/debian-edu-artwork/-/blob/master/art-homeworld/desktop-base/1920x1080.svg

**Comment by julietteTaka** [comment]
Hello Mike,

Thank you for getting in touch with me! I apologize for the delay in my response; my schedule has been quite packed lately.

Unfortunately, I won't be able to take on any additional projects this year. However, I hope to be able to contribute to the next version!

Best regards,

**Comment by sunweaver** [comment]
Dear Juliette,

thanks for your reply. We will create our own desktop backgrounds then. If a new theming of yours gets chosen for Debian 13, maybe you can have in mind, that Debian Edu would love a variant of that theme (esp. background images).

Thanks,
Mike

**Comment by sunweaver** [comment]
Closing...
